name: E2E in custom container (docker)
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Cypress Docker image with Chrome v78
    # and Firefox v70 pre-installed
    container: cypress/browsers:node18.6.0-chrome105-ff104
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          # Specify Browser since container image is compile with Firefox
          browser: firefox
          spec: cypress/e2e/1-getting-started/todo.cy.js
          #build: npm run build
          #start: npm start
          # quote the url to be safe against YML parsing surprises
          #wait-on: 'http://localhost:3000'