name: E2E in custom container (docker)
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    # Cypress Docker image with Chrome v78
    # and Firefox v70 pre-installed
    container: cypress/browsers:node12.13.0-chrome78-ff70
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
          spec: cypress/e2e/1-getting-started/todo.cy.js
          build: npm run build
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'