name: run smoke test on a schedule
on:
  schedule:
    # runs tests every day at 4am
    - cron: '00 11 23 10 *'
    
jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress nightly tests
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/1-getting-started/todo.cy.js
          record: true
          build: npm run build
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}